package com.atguigu.mybatis.pojo;

public class Group {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group.gid
     *
     * @mbggenerated Wed Jul 19 16:59:11 CST 2023
     */
    private Integer gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group.gname
     *
     * @mbggenerated Wed Jul 19 16:59:11 CST 2023
     */
    private String gname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group.gid
     *
     * @return the value of t_group.gid
     *
     * @mbggenerated Wed Jul 19 16:59:11 CST 2023
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group.gid
     *
     * @param gid the value for t_group.gid
     *
     * @mbggenerated Wed Jul 19 16:59:11 CST 2023
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group.gname
     *
     * @return the value of t_group.gname
     *
     * @mbggenerated Wed Jul 19 16:59:11 CST 2023
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group.gname
     *
     * @param gname the value for t_group.gname
     *
     * @mbggenerated Wed Jul 19 16:59:11 CST 2023
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }
}